[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0"]

[project]
name = "journal-assistant"
version = "0.0.1"
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "An agent based bullet journal assistant."
readme = "README.md"
authors = [{ name = "Allen Porter", email = "allen.porter@gmail.com" }]
requires-python = ">=3.12"
classifiers = []
dependencies = [
    "google-adk>=1.21.0",
    "mashumaro>=3.17",
    "PyYAML>=6.0.3",
    "ical>=12.1.2",
]

[project.urls]
Source = "https://github.com/allenporter/journal-assistant"

[tool.setuptools.packages.find]
include = ["journal_assistant*"]
